# change the followings to match your Github username and repo name
baseurl: "/" # the name of your github repo
url: "https://riccardomerolla.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "riccardo.log"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Riccardo Merolla
author-bio: "ricky's brain log"  # change to false to hide
author-image: ricky-ghibli.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/rickydjit
facebook: https://facebook.com/riccardo.merolla
instagram: https://instagram.com/rickydjit
github: https://github.com/riccardomerolla
linkedin: https://www.linkedin.com/in/riccardo-merolla-8298b68
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Github Pages and Jekyll. Theme by Riccardo Merolla."
footer-msg-link: https://github.com/riccardomerolla/riccardomerolla.github.io

# google analytics
google-analytics: G-1111111111

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
